/**
 * 工具栏类型定义
 */

// 工具栏按钮属性
export interface ToolbarButtonProps {
  icon?: string
  label?: string
  title?: string
  active?: boolean
  disabled?: boolean
  showLabel?: boolean
}

// 下拉选项
export interface DropdownOption {
  label: string
  value: string | number
  icon?: string
  disabled?: boolean
}

// 字体选项 - 参考 https://tiptap.dev/docs/editor/extensions/functionality/fontfamily
export const fontFamilyOptions: DropdownOption[] = [
  { label: '默认字体', value: '' },
  { label: '宋体', value: 'SimSun, serif' },
  { label: '黑体', value: 'SimHei, sans-serif' },
  { label: '楷体', value: 'KaiTi, serif' },
  { label: '楷体_GB2312', value: 'KaiTi_GB2312, KaiTi, serif' },
  { label: '仿宋', value: 'FangSong, serif' },
  { label: '仿宋_GB2312', value: 'FangSong_GB2312, FangSong, serif' },
  { label: '华文宋体', value: 'STSong, SimSun, serif' },
  { label: '华文仿宋', value: 'STFangsong, FangSong, serif' },
  { label: '方正仿宋简体', value: 'FZFangSong-Z02S, FangSong, serif' },
  { label: '方正小标宋', value: 'FZXiaoBiaoSong-B05S, SimSun, serif' },
  { label: '微软雅黑', value: 'Microsoft YaHei, sans-serif' },
  { label: 'Arial', value: 'Arial, sans-serif' },
  { label: 'Times New Roman', value: 'Times New Roman, serif' },
  { label: 'Verdana', value: 'Verdana, sans-serif' },
  { label: 'Helvetica', value: 'Helvetica, Arial, sans-serif' },
  { label: 'Calibri', value: 'Calibri, sans-serif' },
  { label: 'Cambria', value: 'Cambria, serif' },
  { label: 'Tahoma', value: 'Tahoma, sans-serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Comic Sans MS', value: 'Comic Sans MS, cursive' },
  { label: 'Impact', value: 'Impact, sans-serif' }
]

// 字号选项 - 使用 px 单位，参考 https://tiptap.dev/docs/editor/extensions/functionality/fontsize
// 中文字号与px对应关系: 初号=56px, 小初=48px, 一号=34.7px≈35px, 小一=32px, 二号=29.3px≈29px
// 小二=24px, 三号=21.3px≈21px, 小三=20px, 四号=18.7px≈19px, 小四=16px, 五号=14px, 小五=12px, 小六=8.7px≈9px
export const fontSizeOptions: DropdownOption[] = [
  { label: '初号', value: '56px' },
  { label: '小初', value: '48px' },
  { label: '一号', value: '35px' },
  { label: '小一', value: '32px' },
  { label: '二号', value: '29px' },
  { label: '小二', value: '24px' },
  { label: '三号', value: '21px' },
  { label: '小三', value: '20px' },
  { label: '四号', value: '19px' },
  { label: '小四', value: '16px' },
  { label: '五号', value: '14px' },
  { label: '小五', value: '12px' },
  { label: '小六', value: '9px' },
  { label: '默认', value: '' },
  { label: '10px', value: '10px' },
  { label: '11px', value: '11px' },
  { label: '12px', value: '12px' },
  { label: '16px', value: '16px' },
  { label: '18px', value: '18px' },
  { label: '20px', value: '20px' },
  { label: '22px', value: '22px' },
  { label: '24px', value: '24px' },
  { label: '26px', value: '26px' },
  { label: '28px', value: '28px' },
  { label: '32px', value: '32px' },
  { label: '36px', value: '36px' },
  { label: '42px', value: '42px' },
  { label: '48px', value: '48px' },
  { label: '72px', value: '72px' },
  { label: '96px', value: '96px' }
]

// 行高选项
export const lineHeightOptions: DropdownOption[] = [
  { label: '默认', value: '' },
  { label: '1', value: '1' },
  { label: '1.15', value: '1.15' },
  { label: '1.5', value: '1.5' },
  { label: '1.75', value: '1.75' },
  { label: '2', value: '2' },
  { label: '2.5', value: '2.5' },
  { label: '3', value: '3' }
]

// 预设颜色
export const presetColors = [
  '#000000',
  '#434343',
  '#666666',
  '#999999',
  '#B7B7B7',
  '#CCCCCC',
  '#D9D9D9',
  '#EFEFEF',
  '#F3F3F3',
  '#FFFFFF',
  '#980000',
  '#FF0000',
  '#FF9900',
  '#FFFF00',
  '#00FF00',
  '#00FFFF',
  '#4A86E8',
  '#0000FF',
  '#9900FF',
  '#FF00FF',
  '#E6B8AF',
  '#F4CCCC',
  '#FCE5CD',
  '#FFF2CC',
  '#D9EAD3',
  '#D0E0E3',
  '#C9DAF8',
  '#CFE2F3',
  '#D9D2E9',
  '#EAD1DC',
  '#DD7E6B',
  '#EA9999',
  '#F9CB9C',
  '#FFE599',
  '#B6D7A8',
  '#A2C4C9',
  '#A4C2F4',
  '#9FC5E8',
  '#B4A7D6',
  '#D5A6BD',
  '#CC4125',
  '#E06666',
  '#F6B26B',
  '#FFD966',
  '#93C47D',
  '#76A5AF',
  '#6D9EEB',
  '#6FA8DC',
  '#8E7CC3',
  '#C27BA0',
  '#A61C00',
  '#CC0000',
  '#E69138',
  '#F1C232',
  '#6AA84F',
  '#45818E',
  '#3C78D8',
  '#3D85C6',
  '#674EA7',
  '#A64D79',
  '#85200C',
  '#990000',
  '#B45F06',
  '#BF9000',
  '#38761D',
  '#134F5C',
  '#1155CC',
  '#0B5394',
  '#351C75',
  '#741B47',
  '#5B0F00',
  '#660000',
  '#783F04',
  '#7F6000',
  '#274E13',
  '#0C343D',
  '#1C4587',
  '#073763',
  '#20124D',
  '#4C1130'
]

// 特殊字符分类
export const specialCharacters: Record<string, string[]> = {
  标点符号: [
    '、',
    '。',
    '·',
    '—',
    '～',
    '‖',
    '…',
    '〔',
    '〕',
    '〈',
    '〉',
    '《',
    '》',
    '「',
    '」',
    '『',
    '』',
    '〖',
    '〗',
    '【',
    '】',
    '±',
    '×',
    '÷',
    '∶',
    '∧',
    '∨',
    '∑',
    '∏',
    '∪',
    '∩',
    '∈',
    '∷',
    '√',
    '⊥',
    '∥',
    '∠',
    '⌒',
    '⊙',
    '∫',
    '∮',
    '≡',
    '≌',
    '≈',
    '∽',
    '∝',
    '≠',
    '≮',
    '≯',
    '≤',
    '≥',
    '∞',
    '∵',
    '∴'
  ],
  数字序号: [
    '①',
    '②',
    '③',
    '④',
    '⑤',
    '⑥',
    '⑦',
    '⑧',
    '⑨',
    '⑩',
    '⑪',
    '⑫',
    '⑬',
    '⑭',
    '⑮',
    '⑯',
    '⑰',
    '⑱',
    '⑲',
    '⑳',
    'Ⅰ',
    'Ⅱ',
    'Ⅲ',
    'Ⅳ',
    'Ⅴ',
    'Ⅵ',
    'Ⅶ',
    'Ⅷ',
    'Ⅸ',
    'Ⅹ',
    'Ⅺ',
    'Ⅻ',
    'ⅰ',
    'ⅱ',
    'ⅲ',
    'ⅳ',
    'ⅴ',
    'ⅵ',
    'ⅶ',
    'ⅷ',
    'ⅸ',
    'ⅹ'
  ],
  希腊字母: [
    'Α',
    'Β',
    'Γ',
    'Δ',
    'Ε',
    'Ζ',
    'Η',
    'Θ',
    'Ι',
    'Κ',
    'Λ',
    'Μ',
    'Ν',
    'Ξ',
    'Ο',
    'Π',
    'Ρ',
    'Σ',
    'Τ',
    'Υ',
    'Φ',
    'Χ',
    'Ψ',
    'Ω',
    'α',
    'β',
    'γ',
    'δ',
    'ε',
    'ζ',
    'η',
    'θ',
    'ι',
    'κ',
    'λ',
    'μ',
    'ν',
    'ξ',
    'ο',
    'π',
    'ρ',
    'σ',
    'τ',
    'υ',
    'φ',
    'χ',
    'ψ',
    'ω'
  ],
  单位符号: [
    '㎎',
    '㎏',
    '㎜',
    '㎝',
    '㎞',
    '㎡',
    '㏄',
    '㏎',
    '㏑',
    '㏒',
    '㏕',
    '℃',
    '℉',
    '°',
    '$',
    '￥',
    '￠',
    '￡',
    '‰',
    '§',
    '№',
    '☆',
    '★',
    '○',
    '●',
    '◎',
    '◇',
    '◆',
    '□',
    '■',
    '△',
    '▲',
    '※',
    '→',
    '←',
    '↑',
    '↓',
    '〓'
  ]
}

// 表情分类
export const emojiCategories = {
  常用: [
    '😀',
    '😃',
    '😄',
    '😁',
    '😆',
    '😅',
    '🤣',
    '😂',
    '🙂',
    '🙃',
    '😉',
    '😊',
    '😇',
    '🥰',
    '😍',
    '🤩',
    '😘',
    '😗',
    '☺️',
    '😚',
    '😙',
    '🥲',
    '😋',
    '😛',
    '😜',
    '🤪',
    '😝',
    '🤑',
    '🤗',
    '🤭',
    '🤫',
    '🤔'
  ],
  手势: [
    '👍',
    '👎',
    '👌',
    '🤌',
    '🤏',
    '✌️',
    '🤞',
    '🤟',
    '🤘',
    '🤙',
    '👈',
    '👉',
    '👆',
    '🖕',
    '👇',
    '☝️',
    '👋',
    '🤚',
    '🖐️',
    '✋',
    '🖖',
    '👏',
    '🙌',
    '🤲',
    '🤝',
    '🙏'
  ],
  表情: [
    '😐',
    '😑',
    '😶',
    '😏',
    '😒',
    '🙄',
    '😬',
    '🤥',
    '😌',
    '😔',
    '😪',
    '🤤',
    '😴',
    '😷',
    '🤒',
    '🤕',
    '🤢',
    '🤮',
    '🤧',
    '🥵',
    '🥶',
    '🥴',
    '😵',
    '🤯',
    '😎',
    '🥳',
    '😲',
    '😨',
    '😰',
    '😥',
    '😢',
    '😭',
    '😱',
    '😖',
    '😣',
    '😞',
    '😓',
    '😩',
    '😫',
    '🥱',
    '😤',
    '😡',
    '😠',
    '🤬'
  ]
}

// 表格对齐方式
export const tableAlignOptions: DropdownOption[] = [
  { label: '左对齐', value: 'left', icon: 'mdi:format-align-left' },
  { label: '居中', value: 'center', icon: 'mdi:format-align-center' },
  { label: '右对齐', value: 'right', icon: 'mdi:format-align-right' }
]

// 模板列表
export const templateList = [
  { id: 'blank', name: '空白文档', description: '创建一个新的空白文档' },
  { id: 'report', name: '工作报告', description: '标准工作报告模板' },
  { id: 'meeting', name: '会议纪要', description: '会议记录模板' },
  { id: 'contract', name: '合同模板', description: '标准合同模板' },
  { id: 'resume', name: '简历模板', description: '个人简历模板' }
]

// 编辑器注入的 Key
export const EditorKey = Symbol('Editor')
